processors = [
    'None',
    'OpenPose',
    'DWPose',
    'MediaPipe Face',
    'Canny',
    'Edge',
    'LineArt Realistic',
    'LineArt Anime',
    'HED',
    'PidiNet',
    'Midas Depth Hybrid',
    'Leres Depth',
    'Zoe Depth',
    'Marigold Depth',
    'Normal Bae',
    'SegmentAnything',
    'MLSD',
    'Shuffle',
    'DPT Depth Hybrid',
    'GLPN Depth',
    'Depth Anything',
]
