from .abnorsett_scheduler import ABNorsettScheduler
from .bong_tangent_scheduler import BongTangentScheduler
from .common_sigma_scheduler import CommonSigmaScheduler
from .deis_scheduler_alt import DEISMultistepScheduler
from .etdrk_scheduler import ETDRKScheduler
from .langevin_dynamics_scheduler import LangevinDynamicsScheduler
from .lawson_scheduler import LawsonScheduler
from .pec_scheduler import PECScheduler
from .res_multistep_scheduler import RESMultistepScheduler
from .res_multistep_sde_scheduler import RESMultistepSDEScheduler
from .res_singlestep_scheduler import RESSinglestepScheduler
from .res_singlestep_sde_scheduler import RESSinglestepSDEScheduler
from .res_unified_scheduler import RESUnifiedScheduler
from .riemannian_flow_scheduler import RiemannianFlowScheduler
from .simple_exponential_scheduler import SimpleExponentialScheduler
from .variants import (
    ABNorsett2MScheduler,
    ABNorsett3MScheduler,
    ABNorsett4MScheduler,
    ArcsineSigmaScheduler,
    DEIS2MScheduler,
    DEIS3MScheduler,
    DEISU1SScheduler,
    DEISU2MScheduler,
    DEISU3MScheduler,
    EasingSigmaScheduler,
    ETDRK2Scheduler,
    ETDRK3AScheduler,
    ETDRK3BScheduler,
    ETDRK4AltScheduler,
    ETDRK4Scheduler,
    EuclideanFlowScheduler,
    HyperbolicFlowScheduler,
    Lawson2AScheduler,
    Lawson2BScheduler,
    Lawson4Scheduler,
    LorentzianFlowScheduler,
    PEC2H2SScheduler,
    PEC2H3SScheduler,
    RES2MScheduler,
    RES2MSDEScheduler,
    RES2SScheduler,
    RES2SSDEScheduler,
    RES3MScheduler,
    RES3MSDEScheduler,
    RES3SScheduler,
    RES3SSDEScheduler,
    RES5SScheduler,
    RES5SSDEScheduler,
    RES6SScheduler,
    RES6SSDEScheduler,
    RESU2MScheduler,
    RESU2SScheduler,
    RESU3MScheduler,
    RESU3SScheduler,
    RESU5SScheduler,
    RESU6SScheduler,
    SigmoidSigmaScheduler,
    SineSigmaScheduler,
    SmoothstepSigmaScheduler,
    SphericalFlowScheduler,
    DEIS1MultistepScheduler,
    DEIS2MultistepScheduler,
    DEIS3MultistepScheduler,
)

__all__ = [  # noqa: RUF022
    # Base
    "RESUnifiedScheduler",
    "RESMultistepScheduler",
    "RESMultistepSDEScheduler",
    "RESSinglestepScheduler",
    "RESSinglestepSDEScheduler",
    "DEISMultistepScheduler",
    "ETDRKScheduler",
    "LawsonScheduler",
    "ABNorsettScheduler",
    "PECScheduler",
    "BongTangentScheduler",
    "RiemannianFlowScheduler",
    "LangevinDynamicsScheduler",
    "CommonSigmaScheduler",
    "SimpleExponentialScheduler",
    # Variants
    "RES2MScheduler",
    "RES3MScheduler",
    "DEIS2MScheduler",
    "DEIS3MScheduler",
    "RES2MSDEScheduler",
    "RES3MSDEScheduler",
    "RES2SScheduler",
    "RES3SScheduler",
    "RES5SScheduler",
    "RES6SScheduler",
    "RES2SSDEScheduler",
    "RES3SSDEScheduler",
    "RES5SSDEScheduler",
    "RES6SSDEScheduler",
    "ETDRK2Scheduler",
    "ETDRK3AScheduler",
    "ETDRK3BScheduler",
    "ETDRK4Scheduler",
    "ETDRK4AltScheduler",
    "Lawson2AScheduler",
    "Lawson2BScheduler",
    "Lawson4Scheduler",
    "ABNorsett2MScheduler",
    "ABNorsett3MScheduler",
    "ABNorsett4MScheduler",
    "PEC2H2SScheduler",
    "PEC2H3SScheduler",
    "EuclideanFlowScheduler",
    "HyperbolicFlowScheduler",
    "SphericalFlowScheduler",
    "LorentzianFlowScheduler",
    "SigmoidSigmaScheduler",
    "SineSigmaScheduler",
    "EasingSigmaScheduler",
    "ArcsineSigmaScheduler",
    "SmoothstepSigmaScheduler",
    "DEISU1SScheduler",
    "DEISU2MScheduler",
    "DEISU3MScheduler",
    "RESU2MScheduler",
    "RESU3MScheduler",
    "RESU2SScheduler",
    "RESU3SScheduler",
    "RESU5SScheduler",
    "RESU6SScheduler",
    "DEIS1MultistepScheduler",
    "DEIS2MultistepScheduler",
    "DEIS3MultistepScheduler",
]

BASE = [
    ("RES Unified", RESUnifiedScheduler),
    ("RES Multistep", RESMultistepScheduler),
    ("RES Multistep SDE", RESMultistepSDEScheduler),
    ("RES Singlestep", RESSinglestepScheduler),
    ("RES Singlestep SDE", RESSinglestepSDEScheduler),
    ("DEIS Multistep", DEISMultistepScheduler),
    ("ETDRK", ETDRKScheduler),
    ("Lawson", LawsonScheduler),
    ("ABNorsett", ABNorsettScheduler),
    ("PEC", PECScheduler),
    ("Common Sigma", CommonSigmaScheduler),
    ("Riemannian Flow", RiemannianFlowScheduler),
]

SIMPLE = [
    ("Bong Tangent", BongTangentScheduler),
    ("Langevin Dynamics", LangevinDynamicsScheduler),
    ("Simple Exponential", SimpleExponentialScheduler),
]

VARIANTS = [
    ("RES 2M", RES2MScheduler),
    ("RES 3M", RES3MScheduler),
    ("DEIS 2M", DEIS2MScheduler),
    ("DEIS 3M", DEIS3MScheduler),
    ("RES 2M SDE", RES2MSDEScheduler),
    ("RES 3M SDE", RES3MSDEScheduler),
    ("RES 2S", RES2SScheduler),
    ("RES 3S", RES3SScheduler),
    ("RES 5S", RES5SScheduler),
    ("RES 6S", RES6SScheduler),
    ("RES 2S SDE", RES2SSDEScheduler),
    ("RES 3S SDE", RES3SSDEScheduler),
    ("RES 5S SDE", RES5SSDEScheduler),
    ("RES 6S SDE", RES6SSDEScheduler),
    ("ETDRK 2", ETDRK2Scheduler),
    ("ETDRK 3A", ETDRK3AScheduler),
    ("ETDRK 3B", ETDRK3BScheduler),
    ("ETDRK 4", ETDRK4Scheduler),
    ("ETDRK 4 Alt", ETDRK4AltScheduler),
    ("Lawson 2A", Lawson2AScheduler),
    ("Lawson 2B", Lawson2BScheduler),
    ("Lawson 4", Lawson4Scheduler),
    ("ABNorsett 2M", ABNorsett2MScheduler),
    ("ABNorsett 3M", ABNorsett3MScheduler),
    ("ABNorsett 4M", ABNorsett4MScheduler),
    ("PEC 2H2S", PEC2H2SScheduler),
    ("PEC 2H3S", PEC2H3SScheduler),
    ("Euclidean Flow", EuclideanFlowScheduler),
    ("Hyperbolic Flow", HyperbolicFlowScheduler),
    ("Spherical Flow", SphericalFlowScheduler),
    ("Lorentzian Flow", LorentzianFlowScheduler),
    ("Sigmoid Sigma", SigmoidSigmaScheduler),
    ("Sine Sigma", SineSigmaScheduler),
    ("Easing Sigma", EasingSigmaScheduler),
    ("Arcsine Sigma", ArcsineSigmaScheduler),
    ("Smoothstep Sigma", SmoothstepSigmaScheduler),
    ("DEIS-U 1S", DEISU1SScheduler),
    ("DEIS-U 2M", DEISU2MScheduler),
    ("DEIS-U 3M", DEISU3MScheduler),
    ("RES-U 2M", RESU2MScheduler),
    ("RES-U 3M", RESU3MScheduler),
    ("RES-U 2S", RESU2SScheduler),
    ("RES-U 3S", RESU3SScheduler),
    ("RES-U 5S", RESU5SScheduler),
    ("RES-U 6S", RESU6SScheduler),
    ("DEIS 1 Multistep", DEIS1MultistepScheduler),
    ("DEIS 2 Multistep", DEIS2MultistepScheduler),
    ("DEIS 3 Multistep", DEIS3MultistepScheduler),
]
